### ISSUE TITLE
手册有一页的水印出现偏移

### ISSUE THREAD

**Issue by xkwxdyy** [xkwxdyy/whuthesis#2]
https://github.com/xkwxdyy/whuthesis/blob/14bcdca75ecb0fe04f83e9868cee533fe05b015e/whuthesis-doc.tex#L165-L176
我使用了上面的代码加水印，效果是 logo 在页面右边，然后编译发现有一页的水印是在中间的：

![image](https://github.com/xkwxdyy/whuthesis/assets/87134063/d87a57a7-6945-4474-b1ac-22c339f3d516)

我不知道是什么原因，本来之前是设置了奇偶不同的，然后发现了这个问题，把奇偶判断去掉也没有用，能麻烦@Sophanatprime 看一下吗？

**Comment by xkwxdyy** [comment]
改成
```latex
\background+(tikz)[./oddevenlogo]{
  % 两种都可以
  \ifodd\c@page
    \node[text opacity = 0.05] at ([shift={(-10em,0em)}]text.east) {\includegraphics[height = \textheight]{logo-black}};
  \else
    \node[text opacity = 0.05] at ([shift={(0em,0em)}]text.west) {\includegraphics[height = \textheight]{logo-black}};
  \fi
}
```
也会发现除了这页居中，这页的后一页的水印也有问题
![image](https://github.com/xkwxdyy/whuthesis/assets/87134063/252acade-eb51-4f14-a825-16886ec1529b)

对于正常的情况要偏右了一些

**Comment by Sophanatprime** [comment]
需要确定的是图片的边界上的点在纸张的哪些个位置。

`\node` 默认使用 `anchor=center`，就是把图片的中心放在指定的坐标上。
`text` 的位置也是变动的，如果要把图片固定在纸张的某个位置，应该考虑使用 `paper`。

例如 `\node[anchor=east] ([xshift=-10cm]paper.east) {..};` 就是把图片右边界的中点放在纸张右边界中点的左边10cm处。

合理使用 `anchor` 和 `text` `paper` 应该就能排出想要的结果了。

**Comment by xkwxdyy** [comment]
非常感谢！改成固定的 `page`（因为没有加 `tikzpagenodes` 包，就用 `cus` 提供的 `page` node）就没问题了。
